#!/bin/bash

if [ -z "$1" ]; then
	headers=*.{hh,h}
else
	headers="$@"
fi

for i in $headers; do
	if [ ! -f $i ]; then
		continue;
	fi

	name=${i%.hh}
	name=${name%.h}

	files="$i"

	if [ -f "$name.cc" ]; then
		files="$files $name.cc"
	fi

	if [ -f "$name.c" ]; then
		files="$files $name.c"
	fi

	$(dirname "$0")/../../scripts/cldoc-dev generate -- --output html $files

	for x in html/xml/*.xml; do
		cp $x ../output/$name-${x#html/xml/}
	done

	rm -rf html
done
