#!/bin/bash

coffee --watch -b --join cldoc.js --compile \
	js/cldoc.coffee		\
	js/page.coffee		\
	js/sidebar.coffee	\
	js/node.coffee		\
	js/type.coffee		\
	js/doc.coffee		\
	js/category.coffee	\
	js/enum.coffee		\
	js/struct.coffee	\
	js/class.coffee		\
	js/namespace.coffee	\
	js/typedef.coffee &

sass --scss -l --watch css/cldoc.scss:cldoc.css &

wait
